
IOSIG_LIB_PATH=/export/home/yyin/install/lib

main: main.o 
	gcc main.o -o main -L${IOSIG_LIB_PATH} -liosig


main.o: main.c
	gcc -finstrument-functions -g -c -o main.o main.c

clean:
	rm *.o *.out

