# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_SIGNATURE_SIGTYPE = descriptor.EnumDescriptor(
  name='SigType',
  full_name='iosig.Signature.SigType',
  filename='SigType',
  values=[
    descriptor.EnumValueDescriptor(
      name='CONTIGUOUS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FIXED_STRIDED', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TWOD_STRIDED', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='THREED_STRIDED', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MARKOV', index=4, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


_SIGNATURE_PATTERN_BASIC = descriptor.Descriptor(
  name='Pattern_Basic',
  full_name='iosig.Signature.Pattern_Basic',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='initial_position', full_name='iosig.Signature.Pattern_Basic.initial_position', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dimension', full_name='iosig.Signature.Pattern_Basic.dimension', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='increment', full_name='iosig.Signature.Pattern_Basic.increment', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repetition', full_name='iosig.Signature.Pattern_Basic.repetition', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_SIGNATURE_PATTERN_ADVANCED = descriptor.Descriptor(
  name='Pattern_Advanced',
  full_name='iosig.Signature.Pattern_Advanced',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset_pattern', full_name='iosig.Signature.Pattern_Advanced.offset_pattern', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size_pattern', full_name='iosig.Signature.Pattern_Advanced.size_pattern', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repetition_pattern', full_name='iosig.Signature.Pattern_Advanced.repetition_pattern', index=2,
      number=3, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_SIGNATURE_PATTERN_2DBASIC = descriptor.Descriptor(
  name='Pattern_2dBasic',
  full_name='iosig.Signature.Pattern_2dBasic',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='initial_position', full_name='iosig.Signature.Pattern_2dBasic.initial_position', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dimension', full_name='iosig.Signature.Pattern_2dBasic.dimension', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='increment', full_name='iosig.Signature.Pattern_2dBasic.increment', index=2,
      number=3, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repetition', full_name='iosig.Signature.Pattern_2dBasic.repetition', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_SIGNATURE_PATTERN_2DADVANCED = descriptor.Descriptor(
  name='Pattern_2dAdvanced',
  full_name='iosig.Signature.Pattern_2dAdvanced',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset_pattern', full_name='iosig.Signature.Pattern_2dAdvanced.offset_pattern', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size_pattern', full_name='iosig.Signature.Pattern_2dAdvanced.size_pattern', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repetition_pattern', full_name='iosig.Signature.Pattern_2dAdvanced.repetition_pattern', index=2,
      number=3, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_SIGNATURE = descriptor.Descriptor(
  name='Signature',
  full_name='iosig.Signature',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='iosig.Signature.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='iosig.Signature.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number_of_access', full_name='iosig.Signature.number_of_access', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initial_position', full_name='iosig.Signature.initial_position', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initial_size', full_name='iosig.Signature.initial_size', index=4,
      number=5, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='basic_pattern', full_name='iosig.Signature.basic_pattern', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adv_pattern', full_name='iosig.Signature.adv_pattern', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='twodbasic_pattern', full_name='iosig.Signature.twodbasic_pattern', index=7,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='twodadv_pattern', full_name='iosig.Signature.twodadv_pattern', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _SIGNATURE_SIGTYPE,
  ],
  options=None)


_SIGNATURELIST = descriptor.Descriptor(
  name='SignatureList',
  full_name='iosig.SignatureList',
  filename='signatureList.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='trace', full_name='iosig.SignatureList.trace', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sig', full_name='iosig.SignatureList.sig', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SIGNATURE_PATTERN_ADVANCED.fields_by_name['offset_pattern'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE_PATTERN_ADVANCED.fields_by_name['size_pattern'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE_PATTERN_ADVANCED.fields_by_name['repetition_pattern'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE_PATTERN_2DBASIC.fields_by_name['increment'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE_PATTERN_2DADVANCED.fields_by_name['offset_pattern'].message_type = _SIGNATURE_PATTERN_2DBASIC
_SIGNATURE_PATTERN_2DADVANCED.fields_by_name['size_pattern'].message_type = _SIGNATURE_PATTERN_2DBASIC
_SIGNATURE_PATTERN_2DADVANCED.fields_by_name['repetition_pattern'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE.fields_by_name['type'].enum_type = _SIGNATURE_SIGTYPE
_SIGNATURE.fields_by_name['basic_pattern'].message_type = _SIGNATURE_PATTERN_BASIC
_SIGNATURE.fields_by_name['adv_pattern'].message_type = _SIGNATURE_PATTERN_ADVANCED
_SIGNATURE.fields_by_name['twodbasic_pattern'].message_type = _SIGNATURE_PATTERN_2DBASIC
_SIGNATURE.fields_by_name['twodadv_pattern'].message_type = _SIGNATURE_PATTERN_2DADVANCED
_SIGNATURELIST.fields_by_name['sig'].message_type = _SIGNATURE

class Signature(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Pattern_Basic(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SIGNATURE_PATTERN_BASIC
  
  class Pattern_Advanced(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SIGNATURE_PATTERN_ADVANCED
  
  class Pattern_2dBasic(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SIGNATURE_PATTERN_2DBASIC
  
  class Pattern_2dAdvanced(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SIGNATURE_PATTERN_2DADVANCED
  DESCRIPTOR = _SIGNATURE

class SignatureList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNATURELIST

